name: Release new version

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: configure NPM credentials
        run: |
          cat <<EOT >> ./.npmrc
          @fortawesome:registry=https://npm.fontawesome.com/
          //npm.fontawesome.com/:_authToken=$NPM_TOKEN
          EOT
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: login to AWS ECR
        id: login
        uses: aws-actions/amazon-ecr-login@v1

      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ steps.login.outputs.registry }}/opendata/drupal:${{ github.sha }}
            ${{ steps.login.outputs.registry }}/opendata/drupal:latest
          secret-files: |
            npmrc=./.npmrc
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release:
    name: release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - build
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: semantic release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 16
          branch: master
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
