name: Test release of new version

on:
  pull_request:
    branches:
      - master

jobs:
  test-build:
    name: test-build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1

      - name: configure NPM credentials
        run: |
          cat <<EOT >> ./.npmrc
          @fortawesome:registry=https://npm.fontawesome.com/
          //npm.fontawesome.com/:_authToken=$NPM_TOKEN
          EOT
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: build docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: |
            opendata/drupal:${{ github.sha }}
            opendata/drupal:latest
          secret-files: |
            npmrc=./.npmrc
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test-release:
    name: test-release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: semantic release
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 16
          branch: master
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
